# ===============================
# CONFIGURACIÓN DEL SERVIDOR
# ===============================
server.port=8082
spring.application.name=coincidencias-service

# ===============================
# BASE DE DATOS (PostgreSQL)
# ===============================
# Como lo ejecutaremos localmente por ahora, usamos localhost
spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/db_coincidencias
spring.datasource.username=postgres
spring.datasource.password=Conce123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# URL para conectar con otros microservicios
notificacion.service.url=https://garnish-showing-glove.ngrok-free.dev/api/notificaciones
reportes.service.url=http://host.docker.internal:8081

# Configuración del Motor de Coincidencias
coincidencias.radio-busqueda-km=5.0