spring.application.name=Usuarios

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/db_usuarios
spring.datasource.username=postgres
spring.datasource.password=Conce123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

spring.jpa.show-sql=true


# CONFIGURACIÓN RESILIENCE4J (CIRCUIT BREAKER)
management.health.circuitbreakers.enabled=true

resilience4j.circuitbreaker.instances.servicioExterno.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.servicioExterno.slidingWindowSize=5
resilience4j.circuitbreaker.instances.servicioExterno.failureRateThreshold=50
resilience4j.circuitbreaker.instances.servicioExterno.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.servicioExterno.permittedNumberOfCallsInHalfOpenState=3

server.port=8080

