server:
  port: 8088

spring:
  application:
    name: bff-gateway
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders: "*"
      routes:
        - id: usuarios_route
          uri: http://usuario_service:8080
          predicates:
            - Path=/api/usuarios/**
        - id: reportes_route
          uri: http://reportes_service:8081
          predicates:
            - Path=/api/reportes/**
        - id: coincidencias_route
          uri: http://coincidencias_service:8082
          predicates:
            - Path=/api/coincidencias/**
        - id: notificaciones_route
          uri: http://notificaciones_app:8083
          predicates:
            - Path=/api/notificaciones/**
        - id: geolocalizacion_route
          uri: http://geolocalizacion-app:8084
          predicates:
            - Path=/api/geolocalizacion/**
        - id: identificacion_route
          uri: http://identificacion_acceso_app:8085
          predicates:
            - Path=/api/identificacion/**
        - id: mascotas_route
          uri: http://mascotas_app:8086
          predicates:
            - Path=/api/mascotas/**
