spring.application.name=IdentificacioAcceso

spring.datasource.url=jdbc:postgresql://host.docker.internal:5430/id_db
spring.datasource.username=postgres
spring.datasource.password=Conce123
spring.datasource.driver-class-name=org.postgresql.Driver

server.port=8085

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

jwt.secret=4f7a2a5e8c4d9b1a3f6e8b2c5d7a9b1c3f5e8b2c4d7a9b1c3f6e8b2c5d7a9b1c
jwt.expirationMs=86400000

usuario.service.url= https://situated-ebony-sermon.ngrok-free.dev