spring.application.name=Reportes

spring.datasource.url=jdbc:postgresql://host.docker.internal:5432/db_reportes
spring.datasource.username=postgres
spring.datasource.password=Conce123
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true


# CONFIGURACIÓN RESILIENCE4J (CIRCUIT BREAKER)
management.health.circuitbreakers.enabled=true

resilience4j.circuitbreaker.instances.servicioUsuarios.registerHealthIndicator=true
resilience4j.circuitbreaker.instances.servicioUsuarios.slidingWindowSize=5
resilience4j.circuitbreaker.instances.servicioUsuarios.failureRateThreshold=50
resilience4j.circuitbreaker.instances.servicioUsuarios.waitDurationInOpenState=10s
resilience4j.circuitbreaker.instances.servicioUsuarios.permittedNumberOfCallsInHalfOpenState=3
server.port=8081